plugins:
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - TODO
        - TO DO
exclude_patterns:
  - '**/*.story.tsx'
  - '**/__mocks__/'
  - '**/__snapshots__/'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '/mock_api_data/'
  - '**/*.d.ts'
