node_defaults: &node
  working_directory: ~/repo
  docker:
    - image: circleci/node

version: 2
jobs:
  build:
    <<: *node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
      - run:
          name: Build application
          command: npm run build
  lint:
    <<: *node
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run TSLint
          command: npm run lint
  install_cc_test_reporter:
    <<: *node
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: ~/repo
          paths:
            - tmp/cc-test-reporter
  test:
    <<: *node
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Notify CodeClimate
          command: ./tmp/cc-test-reporter before-build
      - run:
          name: Run Jest
          command: npm run test-ci
      - run:
          name: Report coverage to CodeClimate
          command: ./tmp/cc-test-reporter after-build --exit-code $?
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - install_cc_test_reporter:
          requires:
            - build
      - test:
          requires:
            - install_cc_test_reporter
