node_defaults: &node
  working_directory: ~/repo
  docker:
    - image: circleci/node

version: 2
jobs:
  build:
    <<: *node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
      - run:
          name: Build application
          command: npm run build
  lint:
    <<: *node
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run TSLint
          command: npm run lint
  test:
    <<: *node
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Jest
          command: npm run test-ci
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
